```{r}
library(here)
library(dplyr)
library(leaflet)
```

```{R}
data_folder <- here("data", "dore")
dore_df <- read.table(file.path(data_folder, "interaction-data.txt"), sep = "\t", header = TRUE)
dore_networks_matrices <- readRDS(file.path(data_folder, "dore_networks_matrices.Rds"))
dore_aggregated_networks_matrices <- readRDS(file.path(data_folder, "dore_aggregated_networks_matrices.Rds"))
dore_supinfo <- read.csv(file.path(data_folder, "dore_supinfo.csv")) |>
    mutate(Longitude_dec = Longitude_dec |> gsub(pattern = ",", replacement = ".") |> as.numeric(), Latitude_dec = Latitude_dec |> gsub(pattern = ",", replacement = ".") |> as.numeric())
```

Chamberlain et al semble intéressant pour notre cas:
```{r}
dore_supinfo[dore_supinfo$Short_ref |> grepl(pattern = "Chamberlain"), ]
```
En effet il y a une étude de Chamberlain et al qui donnent 3 groupes de réseaux.

```{r echo=TRUE, fig.cap="Table pour Chamberlain et al avec les métadonnées des 3 réseaux aggrégés", results="asis"}
library(knitr)
chamberlain_supinfo <- dore_supinfo[dore_supinfo$Idweb %in% c(61, 62, 64), ]
kable(
    dore_supinfo[dore_supinfo$Idweb %in% c(61, 62, 64), -27]
)
```

```{r}
leaflet() %>%
    addTiles() %>%
    # setView(lng = -3.7, lat = 40.4, zoom = 5) %>%
    addMarkers(lat = chamberlain_supinfo$Latitude_dec, lng = chamberlain_supinfo$Longitude_dec, label = paste(chamberlain_supinfo$Location, chamberlain_supinfo$Idweb))
```

```{r}
chamberlain_aggr_bool <- names(dore_aggregated_networks_matrices) |> grepl(pattern = "Chamberlain")
chamberlain_aggr_networks <- dore_aggregated_networks_matrices[chamberlain_aggr_bool]
chamberlain_bool <- names(dore_networks_matrices) |> grepl(pattern = "Chamberlain")
chamberlain_networks <- dore_networks_matrices[chamberlain_bool]

chamberlain_aggr_networks <- lapply(chamberlain_aggr_networks, function(mat) {
    mat[mat > 1] <- 1
    return(mat)
})
chamberlain_networks <- lapply(chamberlain_networks, function(mat) {
    mat[mat > 1] <- 1
    return(mat)
})
```

```{r}
library(future)
plan("multisession")
library(colSBM)
```

```{r}
whole_fit_path <- file.path(data_folder, "chamberlain_full.Rds")
chamberlain1_path <- file.path(data_folder, "chamberlain1.Rds")
chamberlain2_path <- file.path(data_folder, "chamberlain2.Rds")
chamberlain3_path <- file.path(data_folder, "chamberlain3.Rds")
chamberlain123_path <- file.path(data_folder, "chamberlain123.Rds")
```

```{r}
if (!file.exists(whole_fit_path)) {
    fit <- estimate_colBiSBM(netlist = chamberlain_aggr_networks, net_id = names(chamberlain_aggr_networks), colsbm_model = "iid", global_opts = list(verbosity = 2))
    saveRDS(fit, whole_fit_path)
} else {
    fit <- readRDS(whole_fit_path)
}
plot(fit)
fit2plot <- fit$clone()
fit2plot$best_fit$net_id <- paste0(rep("Chamberlain", 3), seq(1, 3))
plot(fit2plot$best_fit, type = "meso", mixture = TRUE, values = TRUE)
```

Besoin de rechercher et lire 

```{r}
library(stringr)
names_list_aggr <- names(chamberlain_aggr_networks) |> str_split("-")
netlist1 <- chamberlain_networks[names_list_aggr[[1]]]
netlist2 <- chamberlain_networks[names_list_aggr[[2]]]
netlist3 <- chamberlain_networks[names_list_aggr[[3]]]

if (!file.exists(chamberlain1_path)) {
    fit1 <- estimate_colBiSBM(netlist = netlist1, colsbm_model = "iid", global_opts = list(verbosity = 2L))
    saveRDS(fit1, chamberlain1_path)
} else {
    fit1 <- readRDS(chamberlain1_path)
}
if (!file.exists(chamberlain2_path)) {
    fit2 <- estimate_colBiSBM(netlist = netlist2, colsbm_model = "iid", global_opts = list(verbosity = 2L))
    saveRDS(fit2, chamberlain2_path)
} else {
    fit2 <- readRDS(chamberlain2_path)
}
if (!file.exists(chamberlain3_path)) {
    fit3 <- estimate_colBiSBM(netlist = netlist3, colsbm_model = "iid", global_opts = list(verbosity = 2L))
    saveRDS(fit3, chamberlain3_path)
} else {
    fit3 <- readRDS(chamberlain3_path)
}
```

```{r}
if (!file.exists(chamberlain123_path)) {
    fit123 <- estimate_colBiSBM(netlist = chamberlain_networks, net_id = names(chamberlain_networks), colsbm_model = "iid", global_opts = list(verbosity = 2L))
    saveRDS(fit123, chamberlain123_path)
} else {
    fit123 <- readRDS(chamberlain123_path)
}
```

En partitionnant 
```{r}
aggr_clust_path <- file.path(data_folder, "chamberlain_clust_aggr.Rds")
clust_path <- file.path(data_folder, "chamberlain_clust.Rds")
```
```{r}
if (!file.exists(aggr_clust_path)) {
    aggr_clustering <- clusterize_bipartite_networks(netlist = chamberlain_aggr_networks, colsbm_model = "iid", global_opts = list(verbosity = 2L), full_collection_init = fit)
    saveRDS(aggr_clustering, aggr_clust_path)
} else {
    aggr_clustering <- readRDS(aggr_clust_path)
}
if (!file.exists(clust_path)) {
    clustering <- clusterize_bipartite_networks(netlist = chamberlain_networks, colsbm_model = "iid", net_id = names(chamberlain_networks), global_opts = list(verbosity = 2L), full_collection_init = fit123)
    saveRDS(clustering, aggr_clust_path)
} else {
    clustering <- readRDS(aggr_clust_path)
}
```
